---
version: 2

multi-ecosystem-groups:
  all-dependencies:
    schedule:
      interval: "weekly"
    pull-request-branch-name:
      separator: "-"

updates:
  - package-ecosystem: "gomod"
    directory: "/"
    patterns:
      - "*"
    multi-ecosystem-group: "all-dependencies"
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/"
    patterns:
      - "*"
    multi-ecosystem-group: "all-dependencies"
    open-pull-requests-limit: 10

  - package-ecosystem: "docker"
    directory: "/"
    patterns:
      - "*"
    multi-ecosystem-group: "all-dependencies"
    open-pull-requests-limit: 10
