---

# Optional dependencies.
# Application should work without them under default configuration.

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: goapp
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  memcached:
    image: memcached:latest
    ports:
      - "11211:11211"

  vault:
    image: vault:1.13.3
    command: server -dev
    cap_add:
      - IPC_LOCK
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=qwerty
    ports:
      - "8200:8200"

  etcd:
    image: bitnami/etcd:latest
    environment:
      - ETCD_LOG_LEVEL=debug
      - ALLOW_NONE_AUTHENTICATION=yes
    ports:
      - "2379:2379"
      - "2380:2380"

  zipkin:
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"

networks:
  default:
    driver: bridge
    name: "goapp_network"
