---

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: goapp
    ports:
      - "5432:5432"

networks:
  default:
    driver: bridge
    name: "goapp_network"
