image:
  repository: ghcr.io/hasansino/go42
  pullPolicy: Always

imagePullSecrets: {}

podSecurityContext: {}
securityContext: {}

nodeSelector: {}
affinity: {}
tolerations: {}

resources:
  requests:
    cpu: 500m
    memory: 128Mi
  limits:
    cpu: 1000m
    memory: 256Mi

service:
  httpPort: 8080
  grpcPort: 50051

env:
  ENVIRONMENT: development
  LOG_LEVEL: debug
  SERVER_HTTP_LISTEN: ":8080"
  SERVER_GRPC_LISTEN: ":50051"

volumeSize: 100Mi

replicaCount: 1

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
