replicaCount: 1

imagePullSecrets: []

image:
  repository: ghcr.io/hasansino/go42
  pullPolicy: Always

serviceAccountAnnotations: {}
podAnnotations: {}
nodeSelector: {}
tolerations: []
affinity: {}

podSecurityContext: {}
securityContext: {}

resources:
  requests:
    cpu: 500m
    memory: 128Mi
  limits:
    cpu: 1000m
    memory: 256Mi

service:
  type: ClusterIP
  httpPort: 8080
  grpcPort: 50051

env:
  ENVIRONMENT: development
  LOG_LEVEL: debug
  SERVER_HTTP_LISTEN: ":8080"
  SERVER_GRPC_LISTEN: ":50051"

ingress:
  className: "nginx"
  annotations: {}
  tls: []
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: Prefix
          port: 8080

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

persistence:
  storageClass: "standard"
  accessMode: ReadWriteOnce
  size: 100Mi