// Code generated by MockGen. DO NOT EDIT.
// Source: chat.go
//
// Generated by this command:
//
//	mockgen -source chat.go -package mocks -destination mocks/mocks.go
//

// Package mocks is a generated GoMock package.
package mocks
