-- +goose Up
CREATE TABLE fruits (
    id int PRIMARY KEY,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP,
    name VARCHAR(36) NOT NULL UNIQUE,

-- +goose Down
DROP TABLE fruits;