# Version file for third-party dependencies.
# Currently is manually maintained.
# @todo Automate this file with a script or tool.

deps:
  swagger-ui-dist:
    version: 5.27.0
    source: https://www.npmjs.com/package/swagger-ui-dist

  swagger-themes:
    version: 1.4.3
    source: https://www.npmjs.com/package/swagger-themes
