// Code generated by MockGen. DO NOT EDIT.
// Source: rate_limit.go
//
// Generated by this command:
//
//	mockgen -source rate_limit.go -package mocks -destination mocks/rate_limit.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockcacheAccessor is a mock of cacheAccessor interface.
type MockcacheAccessor struct {
	ctrl     *gomock.Controller
	recorder *MockcacheAccessorMockRecorder
	isgomock struct{}
}

// MockcacheAccessorMockRecorder is the mock recorder for MockcacheAccessor.
type MockcacheAccessorMockRecorder struct {
	mock *MockcacheAccessor
}

// NewMockcacheAccessor creates a new mock instance.
func NewMockcacheAccessor(ctrl *gomock.Controller) *MockcacheAccessor {
	mock := &MockcacheAccessor{ctrl: ctrl}
	mock.recorder = &MockcacheAccessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcacheAccessor) EXPECT() *MockcacheAccessorMockRecorder {
	return m.recorder
}

// AllowRateLimit mocks base method.
func (m *MockcacheAccessor) AllowRateLimit(ctx context.Context, key string, rate, burst int, ttl time.Duration) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AllowRateLimit", ctx, key, rate, burst, ttl)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AllowRateLimit indicates an expected call of AllowRateLimit.
func (mr *MockcacheAccessorMockRecorder) AllowRateLimit(ctx, key, rate, burst, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AllowRateLimit", reflect.TypeOf((*MockcacheAccessor)(nil).AllowRateLimit), ctx, key, rate, burst, ttl)
}
