// Code generated by MockGen. DO NOT EDIT.
// Source: acessors.go
//
// Generated by this command:
//
//	mockgen -source acessors.go -package mocks -destination mocks/mocks.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	models "github.com/hasansino/go42/internal/auth/models"
	gomock "go.uber.org/mock/gomock"
)

// Mockrepository is a mock of repository interface.
type Mockrepository struct {
	ctrl     *gomock.Controller
	recorder *MockrepositoryMockRecorder
	isgomock struct{}
}

// MockrepositoryMockRecorder is the mock recorder for Mockrepository.
type MockrepositoryMockRecorder struct {
	mock *Mockrepository
}

// NewMockrepository creates a new mock instance.
func NewMockrepository(ctrl *gomock.Controller) *Mockrepository {
	mock := &Mockrepository{ctrl: ctrl}
	mock.recorder = &MockrepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockrepository) EXPECT() *MockrepositoryMockRecorder {
	return m.recorder
}

// SaveUserHistoryRecord mocks base method.
func (m *Mockrepository) SaveUserHistoryRecord(ctx context.Context, record *models.UserHistoryRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveUserHistoryRecord", ctx, record)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveUserHistoryRecord indicates an expected call of SaveUserHistoryRecord.
func (mr *MockrepositoryMockRecorder) SaveUserHistoryRecord(ctx, record any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveUserHistoryRecord", reflect.TypeOf((*Mockrepository)(nil).SaveUserHistoryRecord), ctx, record)
}

// UpdateTokenLastUsed mocks base method.
func (m *Mockrepository) UpdateTokenLastUsed(ctx context.Context, tokenID int, when time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTokenLastUsed", ctx, tokenID, when)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTokenLastUsed indicates an expected call of UpdateTokenLastUsed.
func (mr *MockrepositoryMockRecorder) UpdateTokenLastUsed(ctx, tokenID, when any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTokenLastUsed", reflect.TypeOf((*Mockrepository)(nil).UpdateTokenLastUsed), ctx, tokenID, when)
}

// WithTransaction mocks base method.
func (m *Mockrepository) WithTransaction(ctx context.Context, fn func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTransaction", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithTransaction indicates an expected call of WithTransaction.
func (mr *MockrepositoryMockRecorder) WithTransaction(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTransaction", reflect.TypeOf((*Mockrepository)(nil).WithTransaction), ctx, fn)
}

// MockauthService is a mock of authService interface.
type MockauthService struct {
	ctrl     *gomock.Controller
	recorder *MockauthServiceMockRecorder
	isgomock struct{}
}

// MockauthServiceMockRecorder is the mock recorder for MockauthService.
type MockauthServiceMockRecorder struct {
	mock *MockauthService
}

// NewMockauthService creates a new mock instance.
func NewMockauthService(ctrl *gomock.Controller) *MockauthService {
	mock := &MockauthService{ctrl: ctrl}
	mock.recorder = &MockauthServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockauthService) EXPECT() *MockauthServiceMockRecorder {
	return m.recorder
}

// RecentlyUsedTokens mocks base method.
func (m *MockauthService) RecentlyUsedTokens() map[int]time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecentlyUsedTokens")
	ret0, _ := ret[0].(map[int]time.Time)
	return ret0
}

// RecentlyUsedTokens indicates an expected call of RecentlyUsedTokens.
func (mr *MockauthServiceMockRecorder) RecentlyUsedTokens() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecentlyUsedTokens", reflect.TypeOf((*MockauthService)(nil).RecentlyUsedTokens))
}

// Mocksubscriber is a mock of subscriber interface.
type Mocksubscriber struct {
	ctrl     *gomock.Controller
	recorder *MocksubscriberMockRecorder
	isgomock struct{}
}

// MocksubscriberMockRecorder is the mock recorder for Mocksubscriber.
type MocksubscriberMockRecorder struct {
	mock *Mocksubscriber
}

// NewMocksubscriber creates a new mock instance.
func NewMocksubscriber(ctrl *gomock.Controller) *Mocksubscriber {
	mock := &Mocksubscriber{ctrl: ctrl}
	mock.recorder = &MocksubscriberMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mocksubscriber) EXPECT() *MocksubscriberMockRecorder {
	return m.recorder
}

// Subscribe mocks base method.
func (m *Mocksubscriber) Subscribe(ctx context.Context, topic string, handler func(context.Context, []byte) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscribe", ctx, topic, handler)
	ret0, _ := ret[0].(error)
	return ret0
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MocksubscriberMockRecorder) Subscribe(ctx, topic, handler any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*Mocksubscriber)(nil).Subscribe), ctx, topic, handler)
}
