apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "go42.fqname" . }}-http
  labels: {{- include "go42.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: "nginx-http"
  rules:
    - host: ""
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "go42.fqname" . }}-service-http
                port:
                  name: http

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "go42.fqname" . }}-grpc
  labels: {{- include "go42.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: "nginx-grpc"
  rules:
    - host: ""
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "go42.fqname" . }}-service-grpc
                port:
                  name: grpc
