apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "go42.fqname" . }}-data
  labels:
    {{- include "go42.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}

