apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "go42.fqname" . }}-data
  labels:
    {{- include "go42.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "standard"
  resources:
    requests:
      storage: {{ .Values.volumeSize }}

