name: ai-prepare-env
description: Prepare the environment for AI-related tasks (requires checkout to be done first)

# Prepares the environment for ai agents.

runs:
  using: composite
  steps:
    - name: 'Setup Go'
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'
        cache: true
        cache-dependency-path: |
          **/go.sum
          **/go.mod
    # -----
    - name: 'Download Go modules'
      run: go mod tidy && go mod download
      shell: bash
    # -----
    - name: 'Install protoc plugins for buf'
      run: |
        go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
      shell: bash
    # -----
    - name: 'Cache Homebrew and formulae'
      uses: actions/cache@v4
      with:
        path: |
          /home/linuxbrew/.linuxbrew
          /home/linuxbrew/.cache/Homebrew
        key: homebrew-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('Makefile') }}
        restore-keys: |
          homebrew-${{ runner.os }}-${{ runner.arch }}-
          homebrew-${{ runner.os }}-
    # -----
    - name: 'Setup Homebrew'
      uses: Homebrew/actions/setup-homebrew@main
    # -----
    - name: 'Setup project dependencies'
      run: make setup
      shell: bash
    # -----
    - name: 'Setup MCP servers'
      run: make setup-mcp
      shell: bash
    # -----
    - name: 'Prepare ai environment variables'
      shell: bash
      env:
        HEAD_REF: ${{ github.head_ref }}
        REF_NAME: ${{ github.ref_name }}
        PR_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        SHA: ${{ github.sha }}
        SERVER_URL: ${{ github.server_url }}
        REPOSITORY: ${{ github.repository }}
        RUN_ID: ${{ github.run_id }}
        EVENT_NAME: ${{ github.event_name }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
        ISSUE_NUMBER: ${{ github.event.issue.number }}
        PR_BASE_REF: ${{ github.event.pull_request.base.ref }}
      run: |
        {
          echo "CI=true"
          echo "BRANCH=${HEAD_REF:-$REF_NAME}"
          echo "COMMIT_SHA=${PR_HEAD_SHA:-$SHA}"
          echo "BUILD_URL=${SERVER_URL}/${REPOSITORY}/actions/runs/${RUN_ID}"
          
          # PR-specific variables
          if [ "$EVENT_NAME" = "pull_request" ] || [ "$EVENT_NAME" = "pull_request_review" ] || [ "$EVENT_NAME" = "pull_request_review_comment" ]; then
            echo "PR_NUMBER=${PR_NUMBER:-$ISSUE_NUMBER}"
            echo "TARGET_BRANCH=${PR_BASE_REF:-master}"
          else
            echo "PR_NUMBER="
            echo "TARGET_BRANCH=main"
          fi
        } >> "$GITHUB_ENV"
    # -----
    - name: 'Generate ai agent environment'
      run: make generate-ai
      shell: bash
