---

name: ai-prepare-env
description: 'Prepares the environment for ai agents'

# Prepares the environment for ai agents.

runs:
  using: composite
  steps:
    - name: 'Setup Go'
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'
        cache: true
        cache-dependency-path: |
          **/go.sum
          **/go.mod
    # -----
    - name: 'Download Go modules'
      run: go mod tidy && go mod download
      shell: bash
    # -----
    - name: 'Cache Homebrew and formulae'
      uses: actions/cache@v4
      with:
        path: |
          /home/linuxbrew/.linuxbrew
          /home/linuxbrew/.cache/Homebrew
        key: homebrew-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('Makefile') }}
        restore-keys: |
          homebrew-${{ runner.os }}-${{ runner.arch }}-
          homebrew-${{ runner.os }}-
    # -----
    - name: 'Setup Homebrew'
      uses: Homebrew/actions/setup-homebrew@main
    # -----
    - name: 'Setup project dependencies'
      run: make setup
      shell: bash
    # -----
    - name: 'Setup MCP servers'
      run: make setup-mcp
      shell: bash
    # -----
    - name: 'Build inverted index'
      run: go42x kwb build
      shell: bash
    # -----
    - name: 'Generate ai agent environment'
      env:
        CI: true
        GITHUB_ACTOR: ${{ github.actor }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_EVENT_NAME: ${{ github.event_name }}
        GITHUB_EVENT_PAYLOAD: ${{ toJSON(github.event) }}
        GITHUB_HEAD_REF: ${{ github.head_ref }}
        GITHUB_REF_NAME: ${{ github.ref_name }}
        GITHUB_SHA: ${{ github.sha }}
        GITHUB_SERVER_URL: ${{ github.server_url }}
        GITHUB_RUN_ID: ${{ github.run_id }}
      run: go42x agentenv generate
      shell: bash
