{
 "title": "go42",
 "description": "https://github.com/go42-dev/go42",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "GO42 Dashboard",
   "type": "text",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "options": {
    "content": "```\n░██████╗░░█████╗░░░██╗██╗░█████═╗░\n██╔════╝░██╔══██╗░██╔╝╚█║█════██║░\n██║░░██╗░██║░░██║██╔╝░░╚╝░░███╔═╝░\n██║░░╚██╗██║░░██║███████╗██╔══╝░░░\n╚██████╔╝╚█████╔╝╚════██║███████║░\n░╚═════╝░░╚════╝░░░░░░╚═╝╚══════╝░\n```"
   }
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Application Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Go Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_info{job=\"service\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Architecture",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_info_ext{job=\"service\"}",
     "legendFormat": "{{GOARCH}}"
    }
   ]
  },
  {
   "title": "OS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_info_ext{job=\"service\"}",
     "legendFormat": "{{GOOS}}"
    }
   ]
  },
  {
   "title": "Build Commit",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "application_build{}", "legendFormat": "{{build_commit}}" }
   ]
  },
  {
   "title": "Build Tag",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "application_build{job=\"service\"}",
     "legendFormat": "{{build_tag}}"
    }
   ]
  },
  {
   "title": "Build Date",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "application_build{job=\"service\"}",
     "legendFormat": "{{build_tag}}"
    }
   ]
  },
  { "title": "Go Runtime Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "CPUs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_cpu_count{job=\"service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GOMAXPROCS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_gomaxprocs{job=\"service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_threads{job=\"service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_goroutines{job=\"service\"}",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Mem. Limit",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_memlimit_bytes{job=\"service\"}",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "CGO Calls",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_cgo_calls_count{job=\"service\"}",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Max open FDs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_max_fds{job=\"service\"}",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Open FDs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_open_fds{job=\"service\"}",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Runtime Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_sys_bytes{job=\"service\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "go_memstats_stack_sys_bytes{job=\"service\"}",
     "legendFormat": "Stack"
    },
    {
     "expr": "go_memstats_heap_sys_bytes{job=\"service\"}",
     "legendFormat": "Heap"
    },
    {
     "expr": "go_memstats_alloc_bytes{job=\"service\"}",
     "legendFormat": "Live Heap"
    },
    {
     "expr": "go_memstats_heap_idle_bytes{job=\"service\"}",
     "legendFormat": "Idle Heap"
    },
    {
     "expr": "go_memstats_gc_sys_bytes{job=\"service\"}",
     "legendFormat": "Garbage Collector"
    }
   ]
  },
  {
   "title": "Process Memory",
   "type": "timeseries",
   "description": "RSS — physical RAM used by the process (includes heap, stack, code, and mapped files).  \n\nVirtual — Total virtual memory reserved by the process (includes all memory mappings, not all in RAM).  \n\nShared — File-backed memory (like shared libraries) currently loaded in RAM, excludes heap.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"service\"}",
     "legendFormat": "RSS"
    },
    {
     "expr": "process_virtual_memory_bytes{job=\"service\"}",
     "legendFormat": "Virtual"
    },
    {
     "expr": "process_resident_memory_file_bytes{job=\"service\"}",
     "legendFormat": "Shared"
    }
   ]
  },
  {
   "title": "Heap Objects",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_memstats_heap_objects{job=\"service\"}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Memory Scavenging",
   "type": "timeseries",
   "description": "Total amount of CPU timenthe Go runtime has spent scavenging unused memory pages back to the operating system.\n\nThe scavenger runs in the background to return unused heap memory to the OS.\n\nIt helps reduce the memory footprint of your app, especially for long-lived processes with fluctuating memory usage.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(go_scavenge_cpu_seconds_total{job=\"service\"}[1m])",
     "legendFormat": "Time Spent"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "timeseries",
   "description": "These are part of Pressure Stall Information (PSI) — showing how long your process was waiting or stalled due to lack of CPU, I/O, or memory.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(process_pressure_cpu_waiting_seconds_total{job=\"service\"}[1m])",
     "legendFormat": "CPU Waiting"
    },
    {
     "expr": "rate(process_pressure_cpu_stalled_seconds_total{job=\"service\"}[1m])",
     "legendFormat": "CPU Stalled"
    },
    {
     "expr": "rate(process_pressure_io_waiting_seconds_total{job=\"service\"}[1m])",
     "legendFormat": "I/O Wait"
    },
    {
     "expr": "rate(process_pressure_io_stalled_seconds_total{job=\"service\"}[1m])",
     "legendFormat": "I/O Stalled"
    },
    {
     "expr": "rate(process_pressure_memory_waiting_seconds_total{job=\"service\"}[1m])",
     "legendFormat": "Memory Waiting"
    },
    {
     "expr": "rate(process_pressure_memory_stalled_seconds_total{job=\"service\"}[1m])",
     "legendFormat": "Memory Stalled"
    }
   ]
  },
  {
   "title": "Mutex Wait",
   "type": "timeseries",
   "description": "Cumulative total time that goroutines in a Go application have spent waiting to acquire a locked mutex.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(go_mutex_wait_seconds_total{job=\"service\"}[1m])",
     "legendFormat": "Wait"
    }
   ]
  },
  {
   "title": "CPU Time",
   "type": "timeseries",
   "description": "User — time spent in user space (your Go code).  \nKernel — time spent in kernel/system calls (e.g., I/O, syscalls).",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"service\"}[1m])",
     "legendFormat": "Total"
    },
    {
     "expr": "rate(process_cpu_seconds_user_total{job=\"service\"}[1m])",
     "legendFormat": "User"
    },
    {
     "expr": "rate(process_cpu_seconds_system_total{job=\"service\"}[1m])",
     "legendFormat": "Kernel"
    }
   ]
  },
  {
   "title": "Go Scheduler Latency",
   "type": "timeseries",
   "description": "Go scheduler latency refers to the delay a goroutine experiences between becoming ready to run and actually being scheduled and executed by the Go runtime on an operating system thread.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(go_sched_latencies_seconds_bucket{job=\"service\"}[1m]))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, rate(go_sched_latencies_seconds_bucket{job=\"service\"}[5m]))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.90, rate(go_sched_latencies_seconds_bucket{job=\"service\"}[5m]))",
     "legendFormat": "p90"
    }
   ]
  },
  {
   "title": "GC Frequency",
   "type": "timeseries",
   "description": "GC frequency per second.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(go_gc_pauses_seconds_count{job=\"service\"}[1m])",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "GC Total Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(go_gc_duration_seconds_sum{job=\"service\"}[1m]) / increase(go_gc_duration_seconds_count{job=\"service\"}[1m])",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "GC CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(go_gc_cpu_seconds_total{job=\"service\"}[5m])",
     "legendFormat": "Total"
    },
    {
     "expr": "rate(go_gc_mark_assist_cpu_seconds_total{job=\"service\"}[5m])",
     "legendFormat": "Mark Assist"
    }
   ]
  },
  {
   "title": "GC CPU Fraction",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "go_memstats_gc_cpu_fraction{job=\"service\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "GC STW Duration",
   "type": "heatmap",
   "description": "Duration of \"Stop-the-World\" (STW) pauses caused by the GC.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "rate(go_gc_pauses_seconds_bucket{job=\"service\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GC Trigger",
   "type": "timeseries",
   "description": "Heap size in bytes at which the next GC will trigger.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_next_gc_bytes{job=\"service\"}",
     "legendFormat": "Size"
    }
   ]
  },
  {
   "title": "Last GC",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - go_memstats_last_gc_time_seconds{job=\"service\"}",
     "legendFormat": "Size"
    }
   ]
  },
  { "title": "SQL Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "SQL Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "go_sql_open_connections{}", "legendFormat": "Open ({{db_name}})" },
    { "expr": "go_sql_in_use_connections{}", "legendFormat": "In Use ({{db_name}})" },
    { "expr": "go_sql_idle_connections{}", "legendFormat": "Idle ({{db_name}})" }
   ]
  },
  {
   "title": "SQL Wait Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(go_sql_wait_count_total{}[5m])",
     "legendFormat": "Wait Count ({{db_name}})"
    }
   ]
  },
  {
   "title": "SQL Wait Duration Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(go_sql_wait_duration_seconds_total{}[5m])",
     "legendFormat": "Total Wait Duration ({{db_name}})"
    }
   ]
  },
  { "title": "Service Layer Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "Requests Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(application_http_requests_count{job=\"service\"}[1m]))",
     "legendFormat": "http"
    },
    {
     "expr": "sum(rate(application_grpc_requests_count{job=\"service\"}[1m]))",
     "legendFormat": "grpc"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(application_http_latency_sec_sum{job=\"service\"}[1m])) / sum(rate(application_http_latency_sec_count{job=\"service\"}[1m]))",
     "legendFormat": "http"
    },
    {
     "expr": "sum(rate(application_grpc_latency_sec_sum{job=\"service\"}[1m])) / sum(rate(application_grpc_latency_sec_count{job=\"service\"}[1m]))",
     "legendFormat": "grpc"
    }
   ]
  },
  {
   "title": "Response Codes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(application_http_responses_count{job=\"service\"}[1m])) by(method, status)",
     "legendFormat": "{{method}} {{status}}"
    },
    {
     "expr": "sum(rate(application_grpc_responses_count{job=\"service\"}[1m])) by(method, code, status)",
     "legendFormat": "{{method}} {{code}} {{status}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(application_errors{job=\"service\"}[1m])) by(type)",
     "legendFormat": "{{method}} {{status}}"
    }
   ]
  }
 ]
}