openapi: 3.1.0
info:
  title: 'dummy'
  version: 1.0.0
  description: 'this file is required for redocly to work'
servers:
  - url: 'http://localhost:8080/api/v1'
    description: local
security: []
paths:
  get:
    summary: 'Get dummy'
    operationId: getDummy
    responses:
      '200':
        description: 'OK'
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
                  example: 'Hello, world!'