openapi: 3.1.0
info:
  title: 'example'
  version: 1.0.0
  description: 'go42 example api description'
servers:
  - url: 'http://localhost:8080/api/v1'
    description: local
paths:
  /fruits:
    get:
      tags:
        - fruits
      summary: Get all fruits
      operationId: getFruits
      parameters:
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            default: 10
        - name: offset
          in: query
          required: false
          schema:
            type: integer
            default: 0
      responses:
        '200':
          description: A list of fruits
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Fruit'
    post:
      tags:
        - fruits
      summary: Create a new fruit
      operationId: createFruit
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateFruitRequest'
      responses:
        '201':
          description: Fruit created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fruit'
        '400':
          description: Invalid input
  /fruits/{id}:
    get:
      tags:
        - fruits
      summary: Get a fruit by ID
      operationId: getFruitById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: The requested fruit
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fruit'
        '404':
          description: Fruit not found
    put:
      tags:
        - fruits
      summary: Update a fruit by ID
      operationId: updateFruitById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateFruitRequest'
      responses:
        '200':
          description: Fruit updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fruit'
        '400':
          description: Invalid input
        '404':
          description: Fruit not found
    delete:
      tags:
        - fruits
      summary: Delete a fruit by ID
      operationId: deleteFruitById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Fruit deleted
        '404':
          description: Fruit not found
# ---
components:
  schemas:
    Fruit:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
    CreateFruitRequest:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          minLength: 3
          maxLength: 20
    UpdateFruitRequest:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          minLength: 3
          maxLength: 20
