openapi: 3.1.0
info:
  title: 'tmp'
  version: 1.0.0
  description: 'temporary placeholder spec for redocly merge not to fail'
servers:
  - url: 'http://localhost:8080/api/v1'
    description: local
security: []
paths:
  /:
    get:
      summary: root of all evil
      operationId: root
