package api

// Definitions for code generation related to project api.

// ╭──────────────────────────────╮
// │         GRPC MOCKS           │
// ╰──────────────────────────────╯

// @note grpc code itself is generated by buf using `make generate`

//go:generate mockgen -source gen/sdk/grpc/example/v1/example_grpc.pb.go -package mocks -destination gen/sdk/grpc/example/v1/mocks/example_grpc.go

// ╭──────────────────────────────╮
// │    REST clients and mocks    │
// ╰──────────────────────────────╯

//go:generate mkdir -p gen/sdk/http/v1

//go:generate oapi-codegen -package auth -o gen/sdk/http/v1/auth/auth.gen.go -generate types,client,spec openapi/v1/auth.yml
//go:generate mockgen -source gen/sdk/http/v1/auth/auth.gen.go -package mocks -destination gen/sdk/http/v1/auth/mocks/auth.gen.go

//go:generate oapi-codegen -package example -o gen/sdk/http/v1/example/example.gen.go -generate types,client,spec openapi/v1/example.yml
//go:generate mockgen -source gen/sdk/http/v1/example/example.gen.go -package mocks -destination gen/sdk/http/v1/example/mocks/example.gen.go
