package api

// Definitions for code generation related to project api.

// ╭──────────────────────────────╮
// │         GRPC MOCKS           │
// ╰──────────────────────────────╯

// @note grpc code itself is generated by buf using `make generate`

//go:generate mockgen -source gen/sdk/grpc/auth/v1/auth_grpc.pb.go -package mocks -destination gen/sdk/grpc/auth/v1/mocks/auth_grpc.go

// ╭──────────────────────────────╮
// │    REST clients and mocks    │
// ╰──────────────────────────────╯

//go:generate mkdir -p gen/sdk/http/v1

//go:generate oapi-codegen -package auth -o gen/sdk/http/v1/auth/auth.gen.go -generate types,client,spec openapi/v1/auth.yaml
//go:generate mockgen -source gen/sdk/http/v1/auth/auth.gen.go -package mocks -destination gen/sdk/http/v1/auth/mocks/auth.gen.go

//go:generate oapi-codegen -package chat -o gen/sdk/http/v1/chat/chat.gen.go -generate types,client,spec openapi/v1/chat.yaml
//go:generate mockgen -source gen/sdk/http/v1/chat/chat.gen.go -package mocks -destination gen/sdk/http/v1/chat/mocks/chat.gen.go
