name: unified-workflow

# Unified workflow - linting, testing, and security scanning.
# This workflow is designed for development and testing stages.
#
# Running this workflow too often can ramp-up actions costs significantly.
# One way to mitigate this is to use a self-hosted runners.
# @see https://docs.github.com/en/actions/hosting-your-own-runners
# @see https://github.com/jonico/awesome-runners
#
# @note MacOS runners are 10x more expensive than Linux runners.
#
# @todo `with` arguments are repeated because `with` does not support context
# @see https://github.com/orgs/community/discussions/25246

on:
  workflow_dispatch:
  # push or merge to master
  push:
    branches: [ master ]
  # pull request targeting master branch created or updated
  pull_request:
    branches: [ master ]

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write
  security-events: write

jobs:
  # Stage 1: Linting
  golangci-lint:
    uses: ./.github/workflows/10-golangci-lint.yml
    with:
      runs_on: ubuntu-latest
      continue_on_error: true
  docker-lint:
    uses: ./.github/workflows/10-docker-lint.yml
    with:
      runs_on: ubuntu-latest
      continue_on_error: true
  # Stage 2: Unit tests
  unit-tests:
    uses: ./.github/workflows/20-unit-tests.yml
    needs: [ golangci-lint, docker-lint ]
    with:
      runs_on: ubuntu-latest
      continue_on_error: true
  # Stage 3: Vulnerability Scanning
  security:
    uses: ./.github/workflows/30-security.yml
    needs: [ unit-tests ]
    with:
      runs_on: ubuntu-latest
      continue_on_error: true
  # Stage 4: Build
  docker-build:
    uses: ./.github/workflows/40-docker-build.yml
    needs: [ security ]
    with:
      runs_on: ubuntu-latest
      continue_on_error: false
      service_name: "goapp"
      image_tag: >-
        ${{
          github.event_name == 'pull_request' && github.head_ref || github.ref_name
        }}-${{ github.run_id }}
  docker-security:
    uses: ./.github/workflows/40-docker-security.yml
    needs: [ docker-build ]
    with:
      runs_on: ubuntu-latest
      continue_on_error: true
      service_name: "goapp"
      image_tag: >-
        ${{
          github.event_name == 'pull_request' && github.head_ref || github.ref_name
        }}-${{ github.run_id }}
  # Stage 5: Actions with running application
  integration-tests:
    uses: ./.github/workflows/50-integration-tests.yml
    needs: [ docker-build ]
    with:
      runs_on: ubuntu-latest
      continue_on_error: true
      service_name: "goapp"
      image_tag: >-
        ${{
          github.event_name == 'pull_request' && github.head_ref || github.ref_name
        }}-${{ github.run_id }}
  load-tests:
    uses: ./.github/workflows/50-load-tests.yml
    needs: [ docker-build ]
    with:
      runs_on: ubuntu-latest
      continue_on_error: true
      service_name: "goapp"
      image_tag: >-
        ${{
          github.event_name == 'pull_request' && github.head_ref || github.ref_name
        }}-${{ github.run_id }}
  zap-scan:
    uses: ./.github/workflows/50-zapscan.yml
    needs: [ docker-build ]
    with:
      runs_on: ubuntu-latest
      continue_on_error: true
      service_name: "goapp"
      image_tag: >-
        ${{
          github.event_name == 'pull_request' && github.head_ref || github.ref_name
        }}-${{ github.run_id }}
  # Stage 6: Cleanup
  cleanup:
    uses: ./.github/workflows/60-cleanup.yml
    needs: [ integration-tests, load-tests, zap-scan ]
    with:
      runs_on: ubuntu-latest
      service_name: "goapp"
      image_tag: >-
        ${{
          github.event_name == 'pull_request' && github.head_ref || github.ref_name
        }}-${{ github.run_id }}
