name: dep-submission

# Syncs go dependencies with GitHub dependency submission API.

on:
  # manual trigger
  workflow_dispatch:
  # push or merge to master
  push:
    branches: [ master ]

permissions:
  contents: write

jobs:
  dep-submission:
    if: |
      github.event.head_commit.message != 'initial commit' &&
      !startsWith(github.event.head_commit.message, 'release')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - uses: actions/go-dependency-submission@v2
        with:
          go-mod-path: go.mod
          go-build-target: cmd/app/main.go
