name: docker-lint

# Linter for Dockerfile.
# @see https://github.com/hadolint/hadolint

on:
  workflow_call:
    inputs:
      continue_on_error:
        required: true
        type: boolean
        default: false

permissions:
  contents: read

jobs:
  docker-lint:
    name: docker-lint
    continue-on-error: ${{ inputs.continue_on_error }}
    runs-on:  ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make docker-lint
