name: zap-scan

on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string
      image_tag:
        required: true
        type: string

permissions:
  contents: read

jobs:
  zap-scan:
    name: zap-scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          docker run -d -p 8080:8080 ghcr.io/${{ github.repository_owner }}/${{ inputs.service_name }}:${{ inputs.image_tag }}
          sleep 10
      - uses: zaproxy/action-api-scan@v0.9.0
        with:
          target: 'http://localhost:8080/api/v1/openapi.yml'
          format: openapi
          allow_issue_writing: false
