name: integration-tests

on:
  workflow_call:
    inputs:
      image_tag:
        required: true
        type: string

permissions:
  contents: read

jobs:
  integration-tests:
    name: integration-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          docker run -d -p 8080:8080 ghcr.io/${{ github.repository_owner }}/goapp:${{ inputs.image_tag }}
          sleep 10
      - run: make test-integration
