name: golangci-lint

# Golang linter.
# @see https://golangci-lint.run/

on:
  workflow_dispatch:
    inputs:
      runs_on:
        required: true
        type: string
        default: ubuntu-latest
        description: "runs_on"
      continue_on_error:
        required: true
        type: boolean
        default: false
        description: "continue_on_error"
  workflow_call:
    inputs:
      runs_on:
        required: true
        type: string
        default: ubuntu-latest
      continue_on_error:
        required: true
        type: boolean
        default: false

permissions:
  contents: read

jobs:
  golangci-lint:
    name: golangci-lint
    runs-on: ${{ inputs.runs_on }}
    continue-on-error: ${{ inputs.continue_on_error }}
    # ---
    steps:
      - run: |
          pwd
          ls -la
          find . -name ".golangci.yml"
          cat .golangci.yml || echo "Cannot read file"
      - uses: actions/checkout@v4
      - run: |
          pwd
          ls -la
          find . -name ".golangci.yml"
          cat .golangci.yml || echo "Cannot read file"
      - run: make golangci-lint
