---

name: unified-workflow

# Unified workflow - linting, testing, and security scanning.
# This workflow is designed for development and testing stages.
#
# Actions are executed by `runners` that are provided by GitHub.
# They are not free and billed per minute, 2000 minutes per month are free for private repositories.
# For public repositories, actions are free without limits. (common sense still applies)
# Besides actions, there are also storage limits for packages (like docker images).
#
# Running this workflow too often can ramp-up actions costs significantly.
# One way to mitigate this, is to use a self-hosted runners.
# @see https://docs.github.com/en/actions/hosting-your-own-runners
#
# @note `with` arguments are repeated because `with` does not support context
# @see https://github.com/orgs/community/discussions/25246
# May be fixed with https://github.com/marketplace/actions/dynamic-uses
#
# @tip to use output from job X in job Y, use `needs: [X]` in job Y

on:
  # manual trigger
  workflow_dispatch:
  # push or merge to master
  push:
    branches:
      - master
  # pull request targeting master branch created or updated
  pull_request:
    branches:
      - master

permissions: {}

concurrency:
  group: >-
    ${{ github.event_name == 'pull_request' && format('unified-pr-{0}', github.event.pull_request.number) || format('unified-run-{0}-{1}',
    github.run_id, github.run_attempt) }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:

  # stage 1: linting

  gate:
    name: gate
    runs-on: ubuntu-latest
    steps:
      - name: Start workflow
        run: echo "Workflow started."

  git-lint:
    uses: ./.github/workflows/110-git-lint.yaml
    permissions:
      contents: read
    needs:
      - gate
    with:
      runs_on: ubuntu-latest
      continue_on_error: false
      timeout_minutes: 10

  golangci-lint:
    uses: ./.github/workflows/110-golangci-lint.yaml
    permissions:
      contents: read
    needs:
      - gate
    with:
      runs_on: ubuntu-latest
      continue_on_error: false
      timeout_minutes: 10

  docker-lint:
    uses: ./.github/workflows/110-docker-lint.yaml
    permissions:
      contents: read
    needs:
      - gate
    with:
      runs_on: ubuntu-latest
      continue_on_error: false
      timeout_minutes: 10

  proto-lint:
    uses: ./.github/workflows/110-proto-lint.yaml
    permissions:
      contents: read
    needs:
      - gate
    with:
      runs_on: ubuntu-latest
      continue_on_error: false
      timeout_minutes: 10

  openapi-lint:
    uses: ./.github/workflows/110-openapi-lint.yaml
    permissions:
      contents: read
    needs:
      - gate
    with:
      runs_on: ubuntu-latest
      continue_on_error: false
      timeout_minutes: 10

  markdown-lint:
    uses: ./.github/workflows/110-markdown-lint.yaml
    permissions:
      contents: read
    needs:
      - gate
    with:
      runs_on: ubuntu-latest
      continue_on_error: false
      timeout_minutes: 10

  writing-lint:
    uses: ./.github/workflows/110-writing-lint.yaml
    permissions:
      contents: read
    needs:
      - gate
    with:
      runs_on: ubuntu-latest
      continue_on_error: false
      timeout_minutes: 10

  action-lint:
    uses: ./.github/workflows/110-action-lint.yaml
    permissions:
      contents: read
    needs:
      - gate
    with:
      runs_on: ubuntu-latest
      continue_on_error: false
      timeout_minutes: 10

  sql-lint:
    uses: ./.github/workflows/110-sql-lint.yaml
    permissions:
      contents: read
    needs:
      - gate
    with:
      runs_on: ubuntu-latest
      continue_on_error: false
      timeout_minutes: 10

  project-lint:
    uses: ./.github/workflows/110-project-lint.yaml
    permissions:
      contents: read
    needs:
      - gate
    with:
      runs_on: ubuntu-latest
      continue_on_error: false
      timeout_minutes: 10

  editorconfig-lint:
    uses: ./.github/workflows/110-editorconfig-lint.yaml
    permissions:
      contents: read
    needs:
      - gate
    with:
      runs_on: ubuntu-latest
      continue_on_error: false
      timeout_minutes: 10

  # stage 2: unit tests

  unit-tests:
    uses: ./.github/workflows/120-unit-tests.yaml
    permissions:
      contents: read
    needs:
      - git-lint
      - golangci-lint
      - docker-lint
      - proto-lint
      - openapi-lint
      - markdown-lint
      - writing-lint
      - action-lint
      - sql-lint
      - project-lint
      - editorconfig-lint
    with:
      runs_on: ubuntu-latest
      continue_on_error: false
      timeout_minutes: 10

  # stage 3: pre-build security scans

  security:
    uses: ./.github/workflows/130-security.yaml
    permissions:
      actions: read
      contents: read
      id-token: write
      security-events: write
    needs:
      - unit-tests
    with:
      runs_on: ubuntu-latest
      continue_on_error: false
      timeout_minutes: 15
      codeql_timeout_minutes: 30

  # stage 4: build artifacts

  # since we are using ref name as image tag, we need to prepare it first
  # because it may contain characters that are not allowed in docker image tags
  docker-prepare-tag:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs:
      - unit-tests
    outputs:
      tag: ${{ steps.docker-prepare-tag.outputs.tag }}
    steps:
      - name: Prepare Docker image tag
        id: docker-prepare-tag
        run: |
          IMAGE_TAG="ci-${GITHUB_RUN_ID}-${GITHUB_RUN_ATTEMPT}"
          echo "tag=$IMAGE_TAG" >> "$GITHUB_OUTPUT"
          echo "$IMAGE_TAG"

  docker-build:
    uses: ./.github/workflows/140-docker-build.yaml
    permissions:
      actions: read
      attestations: write
      contents: read
      id-token: write
      packages: write
    needs:
      - docker-prepare-tag
    with:
      runs_on: ubuntu-latest
      continue_on_error: false
      service_name: "go42"
      image_tag: ${{ needs.docker-prepare-tag.outputs.tag }}
      platforms: "linux/amd64,linux/arm64"
      attestation: ${{ github.ref == 'refs/heads/master' }}
      generate_sbom: true
      attestation_sbom: false
      timeout_minutes: 30

  # stage 5: post-build security scans

  # dummy job to create distinct group in GitHub UI
  security-extra-group:
    name: "Security Scans"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs:
      - docker-prepare-tag
      - docker-build
    steps:
      - name: Create security scans group
        run: echo "Grouping job for security scans"

  security-extra:
    uses: ./.github/workflows/140-security-extra.yaml
    permissions:
      actions: read
      contents: read
      packages: read
      security-events: write
    needs:
      - docker-prepare-tag
      - security-extra-group
    with:
      runs_on: ubuntu-latest
      continue_on_error: true
      service_name: "go42"
      image_tag: ${{ needs.docker-prepare-tag.outputs.tag }}
      timeout_minutes: 15

  # stage 6: integration, load & resilience tests

  # dummy job to create distinct group in GitHub UI
  functional-tests-group:
    name: "Integration, Load & Resilience Tests"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs:
      - docker-prepare-tag
      - docker-build
    steps:
      - name: Create integration, load and resilience tests group
        run: echo "Grouping job for tests"

  integration-tests:
    uses: ./.github/workflows/150-integration-tests.yaml
    permissions:
      contents: read
      packages: read
    needs:
      - docker-prepare-tag
      - functional-tests-group
    with:
      runs_on: ubuntu-latest
      continue_on_error: false
      service_name: "go42"
      image_tag: ${{ needs.docker-prepare-tag.outputs.tag }}
      timeout_minutes: 10

  load-tests:
    uses: ./.github/workflows/150-load-tests.yaml
    permissions:
      contents: read
      packages: read
    needs:
      - docker-prepare-tag
      - functional-tests-group
    with:
      runs_on: ubuntu-latest
      continue_on_error: true
      service_name: "go42"
      image_tag: ${{ needs.docker-prepare-tag.outputs.tag }}
      timeout_minutes: 10

  resilience-tests:
    uses: ./.github/workflows/150-resilience-tests.yaml
    permissions:
      contents: read
    needs:
      - docker-prepare-tag
      - functional-tests-group
    with:
      runs_on: ubuntu-latest
      continue_on_error: false
      timeout_minutes: 15

  # Stage 7: cleanup

  cleanup:
    uses: ./.github/workflows/160-cleanup.yaml
    permissions:
      contents: read
      packages: write
    needs:
      - docker-prepare-tag
      - security-extra
      - integration-tests
      - load-tests
      - resilience-tests
    with:
      runs_on: ubuntu-latest
      service_name: "go42"
      image_tag: ${{ needs.docker-prepare-tag.outputs.tag }}
      timeout_minutes: 10
