---

name: docker-lint

# Linter for Dockerfile.
# @see https://github.com/hadolint/hadolint

on:
  workflow_call:
    inputs:
      runs_on:
        required: true
        type: string
      continue_on_error:
        required: true
        type: boolean
      timeout_minutes:
        required: false
        type: number
        default: 10

permissions: {}

jobs:
  docker-lint:
    name: docker-lint
    runs-on: ${{ inputs.runs_on }}
    continue-on-error: ${{ inputs.continue_on_error }}
    timeout-minutes: ${{ inputs.timeout_minutes }}
    permissions:
      contents: read
    # ----
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      # ----
      - name: Run Hadolint
        uses: hadolint/hadolint-action@v3.5.0
        with:
          dockerfile: ./Dockerfile
