name: git-lint

# Git linter.
# Designed to check if user adheres to the project's Git rules.
# Also branch naming have implicit limitations due to docker tag naming rules.

on:
  workflow_dispatch:
    inputs:
      runs_on:
        required: true
        type: string
        default: ubuntu-latest
        description: "runs_on"
      continue_on_error:
        required: true
        type: boolean
        default: false
        description: "continue_on_error"
  workflow_call:
    inputs:
      runs_on:
        required: true
        type: string
      continue_on_error:
        required: true
        type: boolean

permissions: {}

jobs:
  git-lint:
    name: git-lint
    runs-on: ${{ inputs.runs_on }}
    continue-on-error: ${{ inputs.continue_on_error }}
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - env:
          EVENT_NAME: ${{ github.event_name }}
          HEAD_REF: ${{ github.head_ref }}
          REF_NAME: ${{ github.ref_name }}
        run: |
          if [ "$EVENT_NAME" = "pull_request" ]; then
            BRANCH_NAME="$HEAD_REF"
          else
            BRANCH_NAME="$REF_NAME"
          fi
          PATTERN="^[A-Za-z0-9\/_\-\.]+$"
          if ! echo "$BRANCH_NAME" | grep -qE "$PATTERN"; then
            echo "Branch names should follow regex ^[A-Za-z0-9\/_\-\.]+$"
            exit 1
          fi
