name: migrate-lint

# Pgsql migration linter.
# @see https://squawkhq.com/

on:
  workflow_dispatch:
    inputs:
      runs_on:
        required: true
        type: string
        default: self-hosted
        description: "runs_on"
      continue_on_error:
        required: true
        type: boolean
        default: false
        description: "continue_on_error"
  workflow_call:
    inputs:
      runs_on:
        required: true
        type: string
        default: ubuntu-latest
      continue_on_error:
        required: true
        type: boolean
        default: false

permissions:
  contents: read

jobs:
  migrate-lint:
    name: migrate-lint
    runs-on: ${{ inputs.runs_on }}
    continue-on-error: ${{ inputs.continue_on_error }}
    # ---
    steps:
      - uses: actions/checkout@v4
      - uses: sbdchd/squawk-action@v2
        with:
          pattern: "migrate/pgsql/*.sql"
          version: "latest"
          fail-on-violations: true
          # goose will automatically wrap migrations in a transaction
          assume-in-transaction: true


