name: proto-lint

# Protobuf linter.
# @see https://buf.build/docs/lint/

on:
  workflow_dispatch:
    inputs:
      runs_on:
        required: true
        type: string
        default: self-hosted
        description: "runs_on"
      continue_on_error:
        required: true
        type: boolean
        default: false
        description: "continue_on_error"
  workflow_call:
    inputs:
      runs_on:
        required: true
        type: string
        default: ubuntu-latest
      continue_on_error:
        required: true
        type: boolean
        default: false

permissions:
  contents: read
  pull-requests: write

jobs:
  proto-lint:
    name: proto-lint
    runs-on: ${{ inputs.runs_on }}
    continue-on-error: ${{ inputs.continue_on_error }}
    # ---
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-action@v1
        with:
          version: 1.55.0
          lint: true
          format: true
