---

name: editorconfig-lint

# Editorconfig linter.
# @see https://editorconfig-checker.github.io/

on:
  workflow_call:
    inputs:
      runs_on:
        required: true
        type: string
      continue_on_error:
        required: true
        type: boolean
      timeout_minutes:
        required: false
        type: number
        default: 10

permissions: {}

jobs:
  editorconfig-lint:
    name: editorconfig-lint
    runs-on: ${{ inputs.runs_on }}
    continue-on-error: ${{ inputs.continue_on_error }}
    timeout-minutes: ${{ inputs.timeout_minutes }}
    permissions:
      contents: read
    # ----
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: 'Setup Go'
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: 'go.mod'
      - name: 'Install editorconfig-checker'
        run: go install github.com/editorconfig-checker/editorconfig-checker/v3/cmd/editorconfig-checker@v3.11.3
      - name: 'Run editorconfig-checker'
        run: editorconfig-checker -v
