name: git-lint

# Git linter.
# Designed to check if user adheres to the project's Git rules.
# Also branch naming have implicit limitations due to docker tag naming rules.

on:
  workflow_dispatch:
    inputs:
      runs_on:
        required: true
        type: string
        default: ubuntu-latest
        description: 'runs_on'
      continue_on_error:
        required: true
        type: boolean
        default: false
        description: 'continue_on_error'
  workflow_call:
    inputs:
      runs_on:
        required: true
        type: string
      continue_on_error:
        required: true
        type: boolean

permissions: {}

jobs:
  git-lint:
    name: git-lint
    runs-on: ${{ inputs.runs_on }}
    continue-on-error: ${{ inputs.continue_on_error }}
    permissions:
      contents: read
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v5
      - name: 'Validate branch name'
        env:
          # The name of the branch or tag being merged into the base in a pull request.
          # Available only for pull_request and pull_request_target events.
          HEAD_REF: ${{ github.head_ref }}
          # The short name of the branch or tag that triggered the workflow.
          REF_NAME: ${{ github.ref_name }}
        run: |
          # Use HEAD_REF for pull requests, REF_NAME for other events
          # HEAD_REF is empty for non-PR events
          BRANCH_NAME="${HEAD_REF:-$REF_NAME}"
          
          # Clean up the branch name (remove refs/heads/ if present)
          BRANCH_NAME="${BRANCH_NAME#refs/heads/}"
          
          echo "Validating branch name: $BRANCH_NAME"
          
          PATTERN="^[A-Za-z0-9\/_.\-]+$"
          if ! echo "$BRANCH_NAME" | grep -qE "$PATTERN"; then
            echo "Branch names should follow regex ^[A-Za-z0-9\/_.\-]+$"
            echo "Current branch name '$BRANCH_NAME' does not match the pattern"
            exit 1
          fi
          
          echo "Branch name '$BRANCH_NAME' is valid"
