---

name: sql-lint

# Linter for sql migrations.
# @see https://github.com/sqlfluff/sqlfluff

on:
  workflow_call:
    inputs:
      runs_on:
        required: true
        type: string
      continue_on_error:
        required: true
        type: boolean
      timeout_minutes:
        required: false
        type: number
        default: 10

permissions: {}

jobs:
  sql-lint:
    name: sql-lint (${{ matrix.database }})
    runs-on: ${{ inputs.runs_on }}
    continue-on-error: ${{ inputs.continue_on_error }}
    timeout-minutes: ${{ inputs.timeout_minutes }}
    permissions:
      contents: read
    strategy:
      matrix:
        database:
          - sqlite
          - mysql
          - pgsql
        include:
          - database: sqlite
            dialect: sqlite
            path: migrate/sqlite/*.sql
          - database: mysql
            dialect: mysql
            path: migrate/mysql/*.sql
          - database: pgsql
            dialect: postgres
            path: migrate/pgsql/*.sql
    # -----
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      # -----
      - name: 'Run SQLFluff linter'
        run: |-
          docker run --rm \
            --network none \
            --volume "${{ github.workspace }}:/workspace:ro" \
            --workdir /workspace \
            sqlfluff/sqlfluff:4.3.0@sha256:8003e7099a43661bb972bb29b6c66ef0954545586a047bd88cdbdfb6d758f144 \
            lint --config etc/sqlfluff.toml ${{ matrix.path }} --dialect ${{ matrix.dialect }}
