---

name: unit-tests

# Unit tests.

on:
  workflow_dispatch:
    inputs:
      runs_on:
        required: true
        type: string
        default: ubuntu-latest
        description: 'runs_on'
      continue_on_error:
        required: true
        type: boolean
        default: false
        description: 'continue_on_error'
      timeout_minutes:
        required: false
        type: number
        default: 10
        description: 'timeout_minutes'
  workflow_call:
    inputs:
      runs_on:
        required: true
        type: string
      continue_on_error:
        required: true
        type: boolean
      timeout_minutes:
        required: false
        type: number
        default: 10

permissions: {}

jobs:
  unit-tests:
    name: unit-tests
    runs-on: ${{ inputs.runs_on }}
    continue-on-error: ${{ inputs.continue_on_error }}
    timeout-minutes: ${{ inputs.timeout_minutes }}
    permissions:
      actions: read
      contents: read
      pull-requests: write
    # ----
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v7
      - name: 'Setup Go'
        uses: actions/setup-go@v7
        with:
          go-version-file: 'go.mod'
      - name: 'Download Go modules'
        run: go mod download
      - name: 'Run unit tests with race detector'
        run: |-
          go list ./... | grep -v '/tests/' | \
            xargs go test -count=1 -v -race -covermode=atomic -coverprofile=coverage.out
        env:
          CGO_ENABLED: 1 # needed for -race
      - name: 'Check test coverage'
        uses: vladopajic/go-test-coverage@v2
        with:
          config: ./etc/testcoverage.yaml
      - name: 'Upload coverage profile'
        continue-on-error: true
        uses: actions/upload-artifact@v7
        with:
          name: code-coverage
          path: coverage.out
          if-no-files-found: error
      - name: 'Generate coverage report'
        if: github.event_name == 'pull_request'
        id: coverage_report
        continue-on-error: true
        uses: fgrosse/go-coverage-report@e432de98ee94a276e8f666d25bfd76347665f75b # v1.3.1
        with:
          version: v1.3.1
          sha256sum: bce196efd0d22bbdcfa2ab45dc38ad40e96acc5802356b48be358a43958674a0
          coverage-artifact-name: code-coverage
          coverage-file-name: coverage.out
          root-package: github.com/hasansino/go42
          trim: github.com/hasansino/go42
          exclude: '(^|/)(api/gen|mocks)/'
          skip-comment: >-
            ${{ github.event.pull_request.head.repo.full_name != github.repository || github.actor == 'dependabot[bot]' }}
      - name: 'Add coverage report to job summary'
        if: github.event_name == 'pull_request' && steps.coverage_report.outputs.coverage_report != ''
        run: printf '%s\n' "$COVERAGE_REPORT" >> "$GITHUB_STEP_SUMMARY"
        env:
          COVERAGE_REPORT: ${{ steps.coverage_report.outputs.coverage_report }}
