---

name: unit-tests

# Unit tests.

on:
  workflow_dispatch:
    inputs:
      runs_on:
        required: true
        type: string
        default: ubuntu-latest
        description: 'runs_on'
      continue_on_error:
        required: true
        type: boolean
        default: false
        description: 'continue_on_error'
      timeout_minutes:
        required: false
        type: number
        default: 10
        description: 'timeout_minutes'
  workflow_call:
    inputs:
      runs_on:
        required: true
        type: string
      continue_on_error:
        required: true
        type: boolean
      timeout_minutes:
        required: false
        type: number
        default: 10

permissions: {}

jobs:
  unit-tests:
    name: unit-tests
    runs-on: ${{ inputs.runs_on }}
    continue-on-error: ${{ inputs.continue_on_error }}
    timeout-minutes: ${{ inputs.timeout_minutes }}
    permissions:
      contents: read
    # ----
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v7
      - name: 'Setup Go'
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
      - name: 'Download Go modules'
        run: go mod download
      - name: 'Run unit tests with race detector'
        run: |-
          go list ./... | grep -v '/tests/' | \
            xargs go test -count=1 -v -race -covermode=atomic -coverprofile=coverage.out
        env:
          CGO_ENABLED: 1 # needed for -race
      - name: 'Check test coverage'
        uses: vladopajic/go-test-coverage@v2
        with:
          config: ./etc/testcoverage.yaml
