name: docker-build

# Service packaging.
# Builds Dockerfile, which in turn builds golang binary.
# buildx allows building multi-arch images.
# Pushes image to ghcr.io.

on:
  workflow_dispatch:
    inputs:
      runs_on:
        required: true
        type: string
        default: self-hosted
        description: "runs_on"
      continue_on_error:
        required: true
        type: boolean
        default: false
        description: "continue_on_error"
      service_name:
        required: true
        type: string
        default: "go42"
        description: "service_name"
      image_tag:
        required: true
        type: string
        default: "tmp"
        description: "image_tag"
      platforms:
        required: true
        type: string
        default: "linux/amd64"
        description: "platforms"
  workflow_call:
    inputs:
      runs_on:
        required: true
        type: string
        default: ubuntu-latest
      continue_on_error:
        required: true
        type: boolean
        default: false
      service_name:
        required: true
        type: string
      image_tag:
        required: true
        type: string
      platforms:
        required: true
        type: string

permissions:
  packages: write
  contents: read
  attestations: write
  id-token: write

jobs:
  docker-build:
    name: docker-build
    runs-on: ${{ inputs.runs_on }}
    continue-on-error: ${{ inputs.continue_on_error }}
    # ---
    steps:
      - uses: actions/checkout@v4
      - run: echo "go_version=$(grep '^go ' go.mod | awk '{print $2}')" >> $GITHUB_ENV
      - run: echo "commit_hash=$(grep git rev-parse HEAD 2>/dev/null || echo '')" >> $GITHUB_ENV
      - run: echo "release_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo '')" >> $GITHUB_ENV
      # ---
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # ---
      - uses: docker/build-push-action@v6
        with:
          context: ${{ github.workspace }}/
          file: ${{ github.workspace }}/Dockerfile
          platforms: ${{ inputs.platforms }}
          no-cache: true
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ inputs.service_name }}:${{ inputs.image_tag }}
          build-args: |
            GO_VERSION=${{ env.go_version }}
            COMMIT_HASH=${{ env.commit_hash }}
            RELEASE_TAG=${{ env.release_tag }}
