name: docker-build

# Service packaging.
# Builds Dockerfile, which in turn builds golang binary.
# buildx allows building multi-arch images.
# Pushes image to ghcr.io.
#
# @note should be executed only with single platform at a time for cache to work properly.

on:
  workflow_dispatch:
    inputs:
      runs_on:
        required: true
        type: string
        default: ubuntu-latest
        description: "runs_on"
      continue_on_error:
        required: true
        type: boolean
        default: false
        description: "continue_on_error"
      service_name:
        required: true
        type: string
        description: "service_name"
      image_tag:
        required: true
        type: string
        description: "image_tag"
      platforms:
        required: true
        type: choice
        options:
          - linux/amd64
          - linux/arm64
        description: "platforms"
      attestation:
        required: true
        type: boolean
        default: false
        description: "attestation"
      generate_sbom:
        required: true
        type: boolean
        default: false
        description: "generate_sbom"
      attestation_sbom:
        required: true
        type: boolean
        default: false
        description: "attestation_sbom"
  workflow_call:
    inputs:
      runs_on:
        required: true
        type: string
        default: ubuntu-latest
      continue_on_error:
        required: true
        type: boolean
        default: false
      service_name:
        required: true
        type: string
      image_tag:
        required: true
        type: string
      platforms:
        required: true
        type: string
      attestation:
        required: true
        type: boolean
      generate_sbom:
        required: true
        type: boolean
      attestation_sbom:
        required: true
        type: boolean

permissions:
  packages: write
  contents: write
  attestations: write
  id-token: write
  actions: read

jobs:
  docker-build:
    name: docker-build
    runs-on: ${{ inputs.runs_on }}
    continue-on-error: ${{ inputs.continue_on_error }}
    # ---
    steps:
      - uses: actions/checkout@v4
      # ---
      - run: echo "go_version=$(grep '^go ' go.mod | awk '{print $2}')" >> $GITHUB_ENV
      - run: echo "commit_hash=$(git rev-parse HEAD 2>/dev/null || echo '')" >> $GITHUB_ENV
      - run: echo "release_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo '')" >> $GITHUB_ENV
      # ---
      - uses: docker/setup-buildx-action@v3
        with:
          cache-binary: true
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # ---
      - uses: docker/build-push-action@v6
        id: build
        with:
          context: ${{ github.workspace }}/
          file: ${{ github.workspace }}/Dockerfile
          platforms: ${{ inputs.platforms }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ inputs.service_name }}:${{ inputs.image_tag }}
          build-args: |
            GO_VERSION=${{ env.go_version }}
            COMMIT_HASH=${{ env.commit_hash }}
            RELEASE_TAG=${{ env.release_tag }}
          annotations:
            org.opencontainers.image.title: ${{ inputs.service_name }}
            org.opencontainers.image.source: https://github.com/${{ github.repository_owner }}/${{ inputs.service_name }}.git
            org.opencontainers.image.url: https://github.com/${{ github.repository_owner }}/${{ inputs.service_name }}
            org.opencontainers.image.description: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
            org.opencontainers.image.version: ${{ inputs.image_tag }}
            org.opencontainers.image.revision: ${{ env.commit_hash }}
            org.opencontainers.image.licenses: MIT
        env:
          # @see https://reproducible-builds.org/docs/source-date-epoch/
          SOURCE_DATE_EPOCH: 0
          # @see https://github.com/orgs/community/discussions/45969
          BUILDX_NO_DEFAULT_ATTESTATIONS: true
      # ---
      - if: ${{ inputs.generate_sbom }}
        uses: anchore/sbom-action@v0
        with:
          image: ghcr.io/${{ github.repository_owner }}/${{ inputs.service_name }}:${{ inputs.image_tag }}
          format: spdx-json
          output-file: sbom-${{ inputs.service_name }}-${{ inputs.image_tag }}.json
          upload-artifact: true
      # ---
      - if: ${{ inputs.attestation }}
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ghcr.io/${{ github.repository_owner }}/${{ inputs.service_name }}:${{ inputs.image_tag }}
          subject-digest: ${{ steps.build.outputs.digest }}
          show-summary: true
      - if: ${{ inputs.attestation_sbom }}
        uses: actions/attest-sbom@v2
        with:
          subject-name: ghcr.io/${{ github.repository_owner }}/${{ inputs.service_name }}:${{ inputs.image_tag }}
          subject-digest: ${{ steps.build.outputs.digest }}
          sbom-path: sbom-${{ inputs.service_name }}-${{ inputs.image_tag }}.json
          show-summary: true
