name: unit-tests

# Unit tests.

on:
  workflow_dispatch:
    inputs:
      runs_on:
        required: true
        type: string
        default: self-hosted
        description: "runs_on"
      continue_on_error:
        required: true
        type: boolean
        default: false
        description: "continue_on_error"
  workflow_call:
    inputs:
      runs_on:
        required: true
        type: string
        default: ubuntu-latest
      continue_on_error:
        required: true
        type: boolean
        default: false

permissions:
  contents: read

jobs:
  unit-tests:
    name: unit-tests
    runs-on: ${{ inputs.runs_on }}
    continue-on-error: ${{ inputs.continue_on_error }}
    # ---
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - run: go mod download
      - run: go test -count=1 -v -race $(go list ./... | grep -v './tests')
        env:
          CGO_ENABLED: 1
