name: pr-summary

# Automatically generates or updates PR description when a PR is opened or synchronized.

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read
  pull-requests: write
  models: read

jobs:
  check-pr:
    name: check-pr
    runs-on: ubuntu-latest
    outputs:
      should_generate: ${{ steps.pr_check.outputs.should_generate }}
    steps:
      - name: 'Check PR details'
        id: pr_check
        env:
          PR_BODY: ${{ github.event.pull_request.body }}
        run: |
          echo "PR #${{ github.event.pull_request.number }} from ${{ github.event.pull_request.user.login }}"
          echo "Current body length: ${#PR_BODY}"
          
          # Skip if author is a bot
          if [[ "${{ github.event.pull_request.user.type }}" == "Bot" ]]; then
            echo "::notice::Skipping summary generation for bot PR"
            echo "should_generate=false" >> "$GITHUB_OUTPUT"
            exit 0
          fi
          
          # Check if body is empty or just whitespace
          if [ -z "${PR_BODY// }" ]; then
            echo "PR body is empty, will generate summary"
            echo "should_generate=true" >> "$GITHUB_OUTPUT"
          else
            echo "::notice::PR already has a description, skipping summary generation"
            echo "should_generate=false" >> "$GITHUB_OUTPUT"
          fi

  generate-summary:
    name: generate-summary
    needs: check-pr
    if: needs.check-pr.outputs.should_generate == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      models: read
    outputs:
      summary: ${{ steps.ai_summary.outputs.summary }}
    env:
      SUMMARY_ENABLE: ${{ vars.SUMMARY_ENABLE }}
      SUMMARY_MODEL: ${{ vars.SUMMARY_MODEL }}
    steps:
      - name: 'Checkout repository with full history'
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: 'Generate AI Summary'
        id: ai_summary
        uses: ./.github/actions/ai-generate-summary
        with:
          base_ref: ${{ github.event.pull_request.base.sha }}
          head_ref: ${{ github.event.pull_request.head.sha }}
          context_type: pr
          github_token: ${{ secrets.GITHUB_TOKEN }}

  update-pr:
    name: update-pr
    runs-on: ubuntu-latest
    needs: generate-summary
    if: needs.generate-summary.outputs.summary != ''
    steps:
      - name: 'Update PR Description'
        uses: actions/github-script@v7
        env:
          SUMMARY: ${{ needs.generate-summary.outputs.summary }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const summary = process.env.SUMMARY;
            
            if (!summary || summary.trim() === '') {
              console.log('No summary generated, skipping PR update');
              return;
            }
            
            try {
              await github.rest.pulls.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.issue.number,
                body: summary
              });
            } catch (error) {
              console.error('Failed to update PR:', error);
              throw error;
            }
