name: go-vuln-check

# Vulnerability / data leak detection.
# @see https://github.com/gitleaks/gitleaks
# @see https://github.com/securego/gosec
# @see https://pkg.go.dev/golang.org/x/vuln/cmd/govulncheck
# @see https://github.com/sonatype-nexus-community/nancy

on:
  workflow_call:
    inputs:
      continue_on_error:
        required: true
        type: boolean
        default: false

jobs:
  gitleaks:
    name: gitleaks
    runs-on: ubuntu-latest
    continue-on-error: ${{ inputs.continue_on_error }}
    # ---
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  gosec:
    name: gosec
    runs-on: ubuntu-latest
    continue-on-error: ${{ inputs.continue_on_error }}
    env:
      GO111MODULE: on
    # ---
    steps:
      - uses: actions/checkout@v4
      - uses: securego/gosec@master
        with:
          args: -exclude-generated ./...

  govulncheck:
    name: govulncheck
    runs-on: ubuntu-latest
    continue-on-error: ${{ inputs.continue_on_error }}
    # ---
    steps:
      - uses: actions/checkout@v4
      - run: echo "go_version=$(grep '^go ' go.mod | awk '{print $2}')" >> $GITHUB_ENV
      - uses: golang/govulncheck-action@v1
        with:
          repo-checkout: false
          go-version-input: ${{ env.go_version }}

  nancy:
    name: nancy
    runs-on: ubuntu-latest
    continue-on-error: ${{ inputs.continue_on_error }}
    # ---
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - run: go list -json -m all > go.list
      - uses: sonatype-nexus-community/nancy-github-action@main
