name: release-pr-merge

on:
  pull_request:
    types: [closed]

jobs:
  release-pr-merge:
    if: |
      github.event.pull_request.merged == true && 
      startsWith(github.event.pull_request.title, '🚀') && 
      endsWith(github.event.pull_request.title, '🚀')
    name: release-pr-merge
    runs-on: ubuntu-latest
    continue-on-error: false
    # ---
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true