name: release-pr

# Creates a PR to update the appVersion in the Chart.yaml file.
# Merging this PR will trigger deployment.

on:
  workflow_call:
    inputs:
      runs_on:
        required: true
        type: string
        default: ubuntu-latest
      continue_on_error:
        required: true
        type: boolean
        default: false
      tag:
        required: true
        type: string

permissions:
  contents: write
  packages: write
  attestations: write
  id-token: write
  pull-requests: write

jobs:
  release-pr:
    name: release-pr
    runs-on: ${{ inputs.runs_on }}
    continue-on-error: ${{ inputs.continue_on_error }}
    # ---
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: prev_tag
        run: |
          PREVIOUS_TAG=$(git describe --abbrev=0 --tags $(git rev-list --tags --skip=1 --max-count=1) 2>/dev/null || echo "")
          if [ -z "$PREVIOUS_TAG" ]; then
            echo "previous_tag=" >> $GITHUB_OUTPUT
            echo "comparison_url=" >> $GITHUB_OUTPUT
          else
            echo "previous_tag=$PREVIOUS_TAG" >> $GITHUB_OUTPUT
            echo "comparison_url=https://github.com/${{ github.repository }}/compare/$PREVIOUS_TAG...${{ inputs.tag }}" >> $GITHUB_OUTPUT
          fi
      - run: |
          sed -i "s/^appVersion:.*/appVersion: \"${{ inputs.tag }}\"/" infra/helm/app/Chart.yaml
      - uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "auto-release-${{ inputs.tag }}"
          title: "Release ${{ inputs.tag }}"
          body: |
            This is automated release PR.
            Merging this PR will trigger deployment.
            ${{ steps.prev_tag.outputs.previous_tag && format('- Previous version: `{0}`', steps.prev_tag.outputs.previous_tag) || '' }}
            ${{ steps.prev_tag.outputs.comparison_url && format('- Changelog: {0}', steps.prev_tag.outputs.comparison_url) || '' }}
          branch: "auto-release-${{ inputs.tag }}"
          delete-branch: true
          branch-suffix: random
          sign-commits: true
          base: master
          assignees: ${{ github.actor }} # will be whoever created a tag
