name: docker-security

# Vulnerability scan of final artifact. (docker image)
# @see https://trivy.dev/latest/

on:
  workflow_call:
    inputs:
      continue_on_error:
        required: true
        type: boolean
        default: false
      service_name:
        required: true
        type: string
      image_tag:
        required: true
        type: string

permissions:
  packages: read

jobs:
  docker-security:
    name: docker-security
    runs-on: ubuntu-latest
    continue-on-error: ${{ inputs.continue_on_error }}
    # ---
    steps:
      - uses: aquasecurity/trivy-action@0.30.0
        with:
          image-ref: ghcr.io/${{ github.repository_owner }}/${{ inputs.service_name }}:${{ inputs.image_tag }}
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'