name: load-tests

# Load tests.
# Simulates load on application and records statistics.

on:
  workflow_call:
    inputs:
      runs_on:
        required: true
        type: string
        default: ubuntu-latest
      continue_on_error:
        required: true
        type: boolean
        default: false
      service_name:
        required: true
        type: string
      image_tag:
        required: true
        type: string

permissions:
  packages: read

jobs:
  load-tests:
    # ---
    name: load-tests
    runs-on: ${{ inputs.runs_on }}
    continue-on-error: ${{ inputs.continue_on_error }}
    # ---
    services:
      app:
        image: ghcr.io/${{ github.repository_owner }}/${{ inputs.service_name }}:${{ inputs.image_tag }}
        ports:
          - 8080:8080
        env:
          ENVIRONMENT: ci-load-tests
        options: >-
          --health-cmd "curl -f http://localhost:8080/health-check || exit 1"
          --health-start-period 1s
          --health-interval 5s
          --health-timeout 5s
          --health-retries 10
    # ---
    steps:
      - uses: actions/checkout@v4
      - uses: grafana/setup-k6-action@v1
      - uses: grafana/run-k6-action@v1
        with:
          path: ./tests/load/*.js
          flags: --summary-export=k6-summary.json
      # ---
      - uses: actions/upload-artifact@v4
        with:
          name: k6-summary
          path: k6-summary.json
      # ---
      - if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const results = JSON.parse(fs.readFileSync('k6-summary.json', 'utf8'));
            
            const summary = `## Performance Test Results
            
            ### Load Configuration
            - Virtual Users: ${results.metrics.vus_max.value} max (scaled from ${results.metrics.vus.min} to ${results.metrics.vus.max})
            
            ### Request Statistics
            - Total Requests: ${results.metrics.http_reqs.count}
            - Request Rate: ${results.metrics.http_reqs.rate.toFixed(2)} requests/sec
            - Data Received: ${(results.metrics.data_received.count / 1024).toFixed(2)} KB (${results.metrics.data_received.rate.toFixed(2)} KB/s)
            - Data Sent: ${(results.metrics.data_sent.count / 1024).toFixed(2)} KB (${results.metrics.data_sent.rate.toFixed(2)} KB/s)
            
            ### Response Times
            - Avg Response Time: ${results.metrics.http_req_duration.avg.toFixed(2)} ms
            - Median Response Time: ${results.metrics.http_req_duration.med.toFixed(2)} ms
            - Min Response Time: ${results.metrics.http_req_duration.min.toFixed(2)} ms
            - Max Response Time: ${results.metrics.http_req_duration.max.toFixed(2)} ms
            - P90 Response Time: ${results.metrics.http_req_duration["p(90)"].toFixed(2)} ms
            - P95 Response Time: ${results.metrics.http_req_duration["p(95)"].toFixed(2)} ms
            
            ### Health
            - Failed Requests: ${results.metrics.http_req_failed.fails}
            - Success Rate: ${(results.metrics.checks.passes / (results.metrics.checks.passes + results.metrics.checks.fails) * 100).toFixed(2)}%
            
            [View full results](${process.env.GITHUB_SERVER_URL}/${process.env.GITHUB_REPOSITORY}/actions/runs/${process.env.GITHUB_RUN_ID})
            `;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: summary
            });
