name: zap-api-scan

# API vulnerability scan.
# Runs application and performs attacks against it.
# @see https://www.zaproxy.org/

on:
  workflow_dispatch:
    inputs:
      runs_on:
        required: true
        type: string
        default: self-hosted
        description: "runs_on"
      continue_on_error:
        required: true
        type: boolean
        default: false
        description: "continue_on_error"
      service_name:
        required: true
        type: string
        default: "go42"
        description: "service_name"
      image_tag:
        required: true
        type: string
        default: "tmp"
        description: "image_tag"
  workflow_call:
    inputs:
      runs_on:
        required: true
        type: string
        default: ubuntu-latest
      continue_on_error:
        required: true
        type: boolean
        default: false
      service_name:
        required: true
        type: string
      image_tag:
        required: true
        type: string

permissions:
  contents: read

jobs:
  zap-api-scan:
    name: zap-api-scan
    runs-on: ${{ inputs.runs_on }}
    continue-on-error: ${{ inputs.continue_on_error }}
    # ---
    services:
      app:
        image: ghcr.io/${{ github.repository_owner }}/${{ inputs.service_name }}:${{ inputs.image_tag }}
        ports:
          - 8080:8080
        env:
          LOG_LEVEL: warn
          ENVIRONMENT: ci-security-tests
          SERVER_HTTP_LISTEN: :8080
        options: >-
          --health-cmd "curl -f http://localhost:8080/health-check || exit 1"
          --health-start-period 1s
          --health-interval 5s
          --health-timeout 5s
          --health-retries 10
    # ---
    steps:
      - uses: actions/checkout@v4
      # ---
      - uses: zaproxy/action-api-scan@v0.9.0
        with:
          target: 'http://localhost:8080/api/v1/openapi.yml'
          format: openapi
          allow_issue_writing: false
