name: copilot-setup-steps

on:
  # manual trigger
  workflow_dispatch:
  # run on changes to the setup steps
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml
      - .github/workflows/ai-prepare-env.yaml

jobs:
  # this job MUST be called `copilot-setup-steps`
  copilot-setup-steps:
    if: |
      vars.AI_ENABLE != 'false' &&
      vars.COPILOT_ENABLE != 'false'
    uses: ./.github/workflows/500-ai-prepare-env.yaml
