name: ai-generate-summary

# Reusable workflow for generating summaries between two git references.
# @see https://docs.github.com/en/github-models
# @note This workflow is designed to be called from other workflows.
# @note It generates a summary of changes between two git references (branches, tags, or commits).
# @note GitHub models have a free tier with limited usage.

on:
  workflow_call:
    inputs:
      base_ref:
        description: 'Base reference (branch, tag, or commit SHA)'
        required: true
        type: string
      head_ref:
        description: 'Head reference (branch, tag, or commit SHA)'
        required: true
        type: string
      context_type:
        description: 'Context type for summary (release, pr, custom)'
        required: false
        type: string
        default: 'custom'
    outputs:
      summary:
        description: 'Generated summary markdown'
        value: ${{ jobs.ai-generate-summary.outputs.summary }}
      comparison_url:
        description: 'GitHub comparison URL'
        value: ${{ jobs.ai-generate-summary.outputs.comparison_url }}

permissions: {}

jobs:
  ai-generate-summary:
    name: ai-generate-summary
    runs-on: ubuntu-latest
    permissions:
      contents: read
      models: read
    outputs:
      summary: ${{ steps.ai_summary.outputs.summary }}
      comparison_url: ${{ steps.ai_summary.outputs.comparison_url }}
    env:
      SUMMARY_ENABLE: ${{ vars.SUMMARY_ENABLE }}
      SUMMARY_MODEL: ${{ vars.SUMMARY_MODEL }}
    steps:
      - name: Checkout repository with full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate AI Summary
        id: ai_summary
        uses: ./.github/actions/ai-generate-summary
        with:
          base_ref: ${{ inputs.base_ref }}
          head_ref: ${{ inputs.head_ref }}
          context_type: ${{ inputs.context_type }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
