name: Claude Code Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  prepare-env:
    uses: ./.github/workflows/ai-prepare-env.yaml

  claude-review:
    needs: prepare-env
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
      id-token: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Claude Code Review
        id: claude-review
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          use_sticky_comment: true
          model: "claude-opus-4-1-20250805"
          allowed_tools: |
            Bash(go mod tidy*)
            Bash(go mod verify*)
            Bash(go vet*)
            Bash(go test*)
            Bash(make generate*)
            Bash(make lint*)
            Bash(make test-unit*)
            Bash(golangci-lint*)
            Bash(buf lint*)
            Bash(gitleaks*)
            Bash(actionlint*)
