name: Claude Code Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  prepare-env:
    uses: ./.github/workflows/ai-prepare-env.yaml

  claude-review:
    needs: prepare-env
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      issues: read
      id-token: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Claude Code Review
        id: claude-review
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          use_sticky_comment: true
          # model: "claude-opus-4-20250514"
          # allowed_tools: "Bash(npm run test),Bash(npm run lint),Bash(npm run typecheck)"
