name: docker build

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'tag'
        required: true
        default: ''
      latest_tag:
        description: 'latest'
        required: true
        default: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract Go Version
      id: extract-go-version
      run: echo "go_version=$(grep '^go ' go.mod | awk '{print $2}')" >> $GITHUB_ENV

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v6
      with:
        context: ${{ github.workspace }}/
        file: ${{ github.workspace }}/Dockerfile
        platforms: linux/amd64, linux/arm64
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/goapp:${{ github.event.inputs.image_tag }}
        build-args: |
          GO_VERSION: ${{ env.go_version }}
