name: docker-lint

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

jobs:
  docker-lint:
    continue-on-error: true
    name: docker-lint
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - run: make docker-lint
