name: docker-lint

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

jobs:
  docker-lint:
    name: docker-lint
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: hadolint/hadolint-action@v3
        with:
          dockerfile: Dockerfile
