name: go-vuln-check

on:
  workflow_call:
    inputs:
      continue_on_error:
        required: true
        type: boolean
        default: false

jobs:
  # https://pkg.go.dev/golang.org/x/vuln/cmd/govulncheck
  govulncheck:
    continue-on-error: ${{ inputs.continue_on_error }}
    name: govulncheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "go_version=$(grep '^go ' go.mod | awk '{print $2}')" >> $GITHUB_ENV
      - uses: golang/govulncheck-action@v1
        with:
          repo-checkout: false
          go-version-input: ${{ env.go_version }}
  # https://github.com/securego/gosec
  gosec:
    continue-on-error: ${{ inputs.continue_on_error }}
    name: gosec
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - uses: actions/checkout@v4
      - uses: securego/gosec@master
        with:
          args: -exclude-generated ./...
  # https://github.com/sonatype-nexus-community/nancy
  nancy:
    continue-on-error: ${{ inputs.continue_on_error }}
    name: nancy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - run: go list -json -m all > go.list
      - uses: sonatype-nexus-community/nancy-github-action@main
