name: golangci-lint

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

jobs:
  langci-lint:
    name: golangci-lint
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - run: go mod download
      - run: make golangci-lint
