name: vuln-check

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  # https://pkg.go.dev/golang.org/x/vuln/cmd/govulncheck
  govulncheck:
    name: govulncheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: golang/govulncheck-action@v1
  # https://github.com/securego/gosec
  gosec:
    name: gosec
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - uses: actions/checkout@v3
      - uses: securego/gosec@master
        with:
          args: ./...
