name: unified-workflow

# Release.
# Triggered by semver tag push.

on:
  push:
    tags: [ 'v*' ]

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

jobs:
  docker-build:
    uses: ./.github/workflows/40-docker-build.yml
    with:
      runs_on: ubuntu-latest
      continue_on_error: false
      service_name: "go42"
      image_tag: ${{ github.ref_name }}